/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.io.FileNotFoundException;
import java.io.FileOutputStream;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import logica.GestionTrabajadores;
import org.jdesktop.xswingx.PromptSupport;

/**
 *
 * @author Alexi
 */
public class informes extends javax.swing.JInternalFrame {

    /**
     * Creates new form informes
     */
    public informes() {
        initComponents();

        PromptSupport.setPrompt("Buscar trabajador...", txtbuscartrabajador);

        ArrayList<logica.trabajador> lista = new GestionTrabajadores().seleccionar();
        DefaultListModel model = new DefaultListModel();
        for (logica.trabajador aux : lista) {
            model.addElement(aux.getNombre());
        }
        listatrabajadores.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listatrabajadores = new javax.swing.JList();
        txtbuscartrabajador = new javax.swing.JTextField();
        btpdf = new javax.swing.JButton();
        btverinfo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblasistencia = new javax.swing.JLabel();
        lbltipo = new javax.swing.JLabel();
        lblanticipo = new javax.swing.JLabel();
        lblcomentarios = new javax.swing.JLabel();
        lbltelefono = new javax.swing.JLabel();
        lblrut = new javax.swing.JLabel();
        lblnombre = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblsueldo = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Xperia", 0, 18)); // NOI18N
        jLabel1.setText("generacion de informes");

        listatrabajadores.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Pedro Machuca Pereira", "Marcos Wena Loco", "Juan Gabriel Canante", "Diego Juan y Pedro", "Florencio Flores del Campo", "Mario Martinez Mata", "Miguel Segura Dias" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listatrabajadores);

        txtbuscartrabajador.setToolTipText("Buscar Trabajador...");
        txtbuscartrabajador.setName(""); // NOI18N
        txtbuscartrabajador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbuscartrabajadorKeyTyped(evt);
            }
        });

        btpdf.setText("Generar PDF");
        btpdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btpdfActionPerformed(evt);
            }
        });

        btverinfo.setText("Ver Información");
        btverinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btverinfoActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre:");

        jLabel3.setText("RUT:");

        jLabel4.setText("Telefono:");

        jLabel5.setText("Cargo:");

        jLabel6.setText("Días trabajados:");

        jLabel7.setText("Anticipo: $");

        jLabel8.setText("Comentarios:");

        lblasistencia.setText("-");

        lbltipo.setText("-");

        lblanticipo.setText("-");

        lblcomentarios.setText("-");

        lbltelefono.setText("-");

        lblrut.setText("-");

        lblnombre.setText("-");

        jLabel9.setText("Sueldo: $");

        lblsueldo.setText("-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btpdf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btverinfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblsueldo)
                            .addComponent(lblnombre)
                            .addComponent(lblrut)
                            .addComponent(lbltelefono)
                            .addComponent(lblcomentarios)
                            .addComponent(lblanticipo)
                            .addComponent(lbltipo)
                            .addComponent(lblasistencia)))
                    .addComponent(txtbuscartrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtbuscartrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btpdf, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(lblnombre))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(lblrut))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btverinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(lbltelefono)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lbltipo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(lblasistencia))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(lblanticipo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(lblcomentarios))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(lblsueldo))))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btpdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btpdfActionPerformed
        // TODO add your handling code here:
        if (listatrabajadores.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un trabajador de la lista para poder generar un informe PDF");
        } else {
            FileOutputStream archivo;
            try {
                ArrayList<logica.trabajador> lista = new GestionTrabajadores().seleccionarFiltro(listatrabajadores.getSelectedValue().toString());
                String nombre = "";
                String rut = "";
                String telefono = "";
                String cargo = "";
                String asistencia = "";
                String anticipo = "";
                String comentarios = "";
                String sueldo = "";
                for (logica.trabajador aux : lista) {
                    nombre = aux.getNombre();
                    rut = aux.getRut();
                    telefono = Integer.toString(aux.getTelefono());
                    if (aux.getTipo() == 1) {
                        cargo = "Maestro";
                    } else {
                        if (aux.getTipo() == 2) {
                            cargo = "Ayudante";
                        } else {
                            cargo = "Principiante";
                        }
                    }
                    asistencia = Double.toString(aux.getAsistencia());
                    anticipo = Integer.toString(aux.getAnticipo());
                    comentarios = aux.getComentarios();
                    sueldo = Integer.toString(aux.getSueldo());
                }
                Calendar actual = Calendar.getInstance();
                int ano = 2015;
                int mes = actual.get(Calendar.MONTH);
                int dia = actual.get(Calendar.DAY_OF_MONTH);
                java.sql.Date fechahoy = new java.sql.Date(ano, mes, dia);
                String date = fechahoy.toString();
                archivo = new FileOutputStream("C:/Informes/Informe " + nombre + " " + date + ".pdf");
                Document documento = new Document();
                PdfWriter.getInstance(documento, archivo);
                documento.open();
                documento.addAuthor("WorkPay");
                documento.addTitle("WorkPay");  
                documento.add(new Paragraph("Nombre: " + nombre));
                documento.add(new Paragraph(" "));
                documento.add(new Paragraph("RUT: " + rut));
                documento.add(new Paragraph(" "));
                documento.add(new Paragraph("Teléfono: " + telefono));
                documento.add(new Paragraph(" "));
                documento.add(new Paragraph("Cargo: " + cargo));
                documento.add(new Paragraph(" "));
                documento.add(new Paragraph("Días trabajados: " + asistencia));
                documento.add(new Paragraph(" "));
                documento.add(new Paragraph("Anticipo: $" + anticipo));
                documento.add(new Paragraph(" "));
                documento.add(new Paragraph("Comentarios: " + comentarios));
                documento.add(new Paragraph(" "));
                documento.add(new Paragraph("Sueldo: $" + sueldo));
                documento.close();
                JOptionPane.showMessageDialog(null, "Informe creado exitosamente");
                Process p = Runtime.getRuntime().exec("explorer.exe C:\\Informes");
            } catch (FileNotFoundException | DocumentException ex) {
                Logger.getLogger(informes.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "Error al generar el Informe PDF!");
            } catch (IOException ex) {
                Logger.getLogger(informes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btpdfActionPerformed

    private void txtbuscartrabajadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscartrabajadorKeyTyped
        // TODO add your handling code here:
        String nombre = txtbuscartrabajador.getText().toUpperCase();
        ArrayList<logica.trabajador> lista = new GestionTrabajadores().seleccionarFiltro(nombre);
        DefaultListModel model = new DefaultListModel();
        for (logica.trabajador aux : lista) {
            model.addElement(aux.getNombre());
        }
        listatrabajadores.setModel(model);
    }//GEN-LAST:event_txtbuscartrabajadorKeyTyped

    private void btverinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btverinfoActionPerformed
        // TODO add your handling code here:
        if (listatrabajadores.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un trabajador de la lista para poder ver su información");
        } else {
            ArrayList<logica.trabajador> lista = new GestionTrabajadores().seleccionarFiltro(listatrabajadores.getSelectedValue().toString());
            for (logica.trabajador aux : lista) {
                lblanticipo.setText(Integer.toString(aux.getAnticipo()));
                lblasistencia.setText(Double.toString(aux.getAsistencia()));
                lblcomentarios.setText(aux.getComentarios());
                lblnombre.setText(aux.getNombre());
                lblrut.setText(aux.getRut());
                lbltelefono.setText(Integer.toString(aux.getTelefono()));
                lblsueldo.setText(Integer.toString(aux.getSueldo()));
                if (aux.getTipo() == 1) {
                    lbltipo.setText("Maestro");
                } else {
                    if (aux.getTipo() == 2) {
                        lbltipo.setText("Ayudante");
                    } else {
                        lbltipo.setText("Principiante");
                    }
                }
            }
        }
    }//GEN-LAST:event_btverinfoActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btpdf;
    private javax.swing.JButton btverinfo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblanticipo;
    private javax.swing.JLabel lblasistencia;
    private javax.swing.JLabel lblcomentarios;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JLabel lblrut;
    private javax.swing.JLabel lblsueldo;
    private javax.swing.JLabel lbltelefono;
    private javax.swing.JLabel lbltipo;
    private javax.swing.JList listatrabajadores;
    private javax.swing.JTextField txtbuscartrabajador;
    // End of variables declaration//GEN-END:variables
}
